### ISSUE TITLE
Incorrect int64 conversion when compiled to JavaScript?

### ISSUE THREAD

**Issue by tav** [dart-lang/fixnum#37]
Hi, I'm new to Dart, so my apologies if I've missed something obvious. It seems that either the Dart compiler or the `fixnum` package gets the conversion wrong when compiling to JavaScript.

For example, the following code:

```dart
import 'package:fixnum/fixnum.dart' as fixnum;

main() {
  var x = new fixnum.Int64(9223372036854775807);
  print(x);
  print(x + 1);
}
```

Outputs correctly when run with `dart`:

```
9223372036854775807
-9223372036854775808
```

But when running with `dart2js`, it outputs:

```
-9223372036854775808
-9223372036854775807
```

Is this expected behaviour?

**Comment by rakudrama** [comment]
This is the expected behaviour when compiled to JavaScript.

dart2js and ddc compile int and double to JavaScript numbers, which are really IEEE 754 doubles,
JavaScript numbers can't represent `9223372036854775807` exactly.
The number in the program is actually the nearest number, `9223372036854775808`, which is 2^63.
When viewed as a signed 64-bit value, the sign bit is set, giving -9223372036854775808.

The problem is before any Int64 code.

The whole reason for having the `Int64` class is to represent values exactly that cannot be represented as JavaScript numbers.  If JavaScript numbers could represent 64-bit values, we would not have written Int64.

To ensure exact values, sse `Int64.parse` to convert from a String.
