### ISSUE TITLE
Max value to int is min value on web

### ISSUE THREAD

**Issue by Herrera93** [dart-lang/fixnum#75]
I tried the converting `Int64.MAX_VALUE` to int and back to `Int64` on web and I get the min value instead:
```dart
    print(Int64.MAX_VALUE.toInt()); // 9223372036854776000
    print(Int64(Int64.MAX_VALUE.toInt())); // -9223372036854775808
    print(Int64(Int64.MAX_VALUE.toInt()).isMaxValue); // false
    print(Int64(Int64.MAX_VALUE.toInt()).isNegative); // true
    print(Int64(Int64.MAX_VALUE.toInt()).isMinValue); // true
```

Is this the expected behavior ? This works thought:
```dart
    print(Int64.parseInt(Int64.MAX_VALUE.toString())); // 9223372036854775807
    print(Int64.parseInt(Int64.MAX_VALUE.toString()).isMaxValue); // true
 ```

**Comment by rakudrama** [comment]
This is expected.

On the web, `int` values are represented as JavaScript numbers, which behave like IEEE-754 binary floating point values. They work well up to about 53 bits (or about 15 decimal digits), and then become approximate with loss of precision in the lower bits.

The result of `toInt` is a JavaScript number which cannot represent 9223372036854775807. The value is rounded to the nearest value that can be represented, 9223372036854775808, which so happens to ripple the carry all the way to the next power of two, leading to a negative interpretation when converted back into `Int64` (2's complement 64-bit format).
The rounded `int` value prints as 9223372036854776000 because that is the 'cleanest' number that also rounds to the the exact same JavaScript number.

As you have discovered, if you need to store `Int64` values in another format, Strings are a good option.

**Comment by cbracken** [comment]
Closing as working as expected. This is [documented](https://github.com/dart-lang/fixnum/blob/9d90a12c0554554c9f3438d610014c713f8be0d0/lib/src/intx.dart#L170-L171) on the `toInt` method, but improvements to the wording are always welcome.
